version: '3.3'
services:
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "12800:12800"
    environment:
      - SPP_HTTP_SSL_ENABLED=false
      - SPP_JWT_ENABLED=false
  skywalking-oap:
    image: sourceplusplus/spp-oap-server:latest
    container_name: skywalking-oap
    hostname: skywalking-oap
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_HTTP_SSL_ENABLED=false
